# Secret containing DATABASE_URL
# Note: This is a placeholder. In production, use proper secret management!

apiVersion: v1
kind: Secret
metadata:
  name: checkout-secrets
  namespace: production
type: Opaque
stringData:
  database-url: "postgresql://checkout_user:CHANGEME@postgres.production.svc.cluster.local:5432/checkout_db"
  # In real production:
  # - Never commit actual secrets to git
  # - Use tools like Sealed Secrets, External Secrets Operator, or Vault
  # - Rotate secrets regularly
