# Advanced HPA with scaling behavior
# Chapter 4: The Resource Crunch

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: advanced-hpa
  namespace: production
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: notification-service
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # Wait 5 min before scaling down
      policies:
      - type: Percent
        value: 50          # Remove max 50% of pods
        periodSeconds: 60
      - type: Pods
        value: 2           # Or remove 2 pods
        periodSeconds: 60
      selectPolicy: Min    # Use more conservative
    scaleUp:
      stabilizationWindowSeconds: 0    # Scale up immediately
      policies:
      - type: Percent
        value: 100         # Double pods if needed
        periodSeconds: 15
      - type: Pods
        value: 4           # Or add 4 pods
        periodSeconds: 15
      selectPolicy: Max    # Use more aggressive
